[tool.poetry]
name = "eviction_tracker"
version = "1.0.0"
description = "A court data site for use by the people"
authors = ["Greg Ziegan <greg.ziegan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9.3"
Flask = "^2.1.2"
click = "^8.1.3"
gspread = "^5.4.0"
SQLAlchemy = "^1.4.37"
Flask-SQLAlchemy = "^2.5.1"
marshmallow = "^3.16.0"
marshmallow-sqlalchemy = "^0.28.0"
Flask-RESTy = "^4.0.2"
Flask-Login = "^0.6.1"
Flask-Security-Too = "^4.1.4"
bcrypt = "^3.2.2"
twilio = "^7.9.2"
phonenumbers = "^8.12.49"
pyquery = "^1.4.3"
nameparser = "^1.1.1"
APScheduler = "^3.9.1"
Flask-APScheduler = "^1.12.3"
usaddress = "^0.5.10"
datadog = "^0.44.0"
python-json-logger = "^2.0.2"
gspread-formatting = "^1.0.6"
jellyfish = "^0.9.0"
Flask-Cors = "^3.0.10"
gunicorn = "^20.1.0"
pdf2image = "^1.16.0"
"pdfminer.six" = "^20220524"
selenium = "^4.2.0"
pytesseract = "^0.3.9"
Flask-Mail = "^0.9.1"
Flask-Testing = "^0.8.1"
flask-marshmallow = "^0.14.0"
Flask-Migrate = "^3.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pdbpp = "^0.10.3"
python-language-server = "^0.36.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry>=1.1.13"]
build-backend = "poetry.masonry.api"
