[tool.poetry]
name = "eviction-tracker"
version = "1.0.0"
description = "A court data site for use by the people"
authors = ["Greg Ziegan <greg.ziegan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.9.1"
Flask = "^2.0.1"
click = "^8.0.1"
gspread = "^4.0.1"
flask-marshmallow = "^0.14.0"
marshmallow-sqlalchemy = "^0.26.1"
Flask-SQLAlchemy = "^2.5.1"
Flask-Migrate = "^3.1.0"
Flask-RESTy = "^1.8.0"
Flask-Login = "^0.5.0"
SQLAlchemy = "^1.4.23"
Flask-Security-Too = "^4.1.0"
bcrypt = "^3.2.0"
twilio = "^6.63.2"
phonenumbers = "^8.12.31"
pyquery = "^1.4.3"
nameparser = "^1.0.6"
APScheduler = "^3.7.0"
Flask-APScheduler = "1.12.1"
usaddress = "^0.5.10"
datadog = "^0.42.0"
python-json-logger = "^2.0.2"
gspread-formatting = "^1.0.4"
jellyfish = "^0.8.8"
Flask-Cors = "^3.0.10"
Babel = "^2.9.1"
PyYAML = "^5.4.1"
gunicorn = "^20.1.0"
pdf2image = "^1.16.0"
"pdfminer.six" = "20201018"
selenium = "^4.0.0"
tzlocal = "^2.1"
circuitbreaker = "^1.3.2"
pillow = "^9.0.0"
pytesseract = "^0.3.8"
flask-log-request-id = "^0.10.1"
Flask-Mail = "^0.9.1"
Flask-WTF = "^1.0.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
python-language-server = "^0.36.2"
Flask-Testing = "^0.8.1"
pytest = "^6.2.5"
pdbpp = "^0.10.3"

[build-system]
requires = ["poetry>=1.1.8"]
build-backend = "poetry.masonry.api"
