name: Continuous Integration

on: push

env:
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  ENV: production
  ROLLBAR_CLIENT_TOKEN: ${{ secrets.ROLLBAR_CLIENT_TOKEN }}
  VERSION: test

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: red-door-collective 
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop --impure -c ./test-setup.sh /tmp
      - run: nix develop --impure -c pytest -m "not smoke or regression"

  integration_tests:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: red-door-collective 
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop --impure -c ./test-setup.sh /tmp
      - run: nix develop --impure -c pytest -m "smoke or regression"

  compute_tags:
    name: Compute Tags
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.compute_tag.outputs.next_tag }}
      last_release_tag: ${{ steps.compute_tag.outputs.previous_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute release tag
        id: compute_tag
        uses: craig-day/compute-tag@v13
        with:
          github_token: ${{ github.token }}
          version_scheme: continuous
          version_type: major
          
  commit_assets:
    runs-on: ubuntu-latest
    name: Commit Assets
    needs:
      - compute_tags
      - unit_tests
      - integration_tests
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v20
      - uses: nick-invision/retry@v2
        name: Build application
        with:
          max_attempts: 3
          timeout_minutes: 3
          retry_on: error
          command: ./scripts/build-ui
        env:
          VERSION: ${{ needs.compute_tags.outputs.release_tag }}
      - id: commit_assets
        run: |
          set -ex -o pipefail
          git config user.name "Release Bot"
          git config user.email "not.real@example.com"
          git add -f rdc_website/static_pages
          git commit -m "Build application for $GITHUB_SHA"
          
          BRANCH_NAME="$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///')-deploy"

          git push --force origin "HEAD:refs/heads/$BRANCH_NAME"
          echo "::set-output name=git_branch::$BRANCH_NAME"
  
  release:
    name: Create Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: 
      - commit_assets
      - compute_tags
    steps:
      # Checkout the ref that contains artifacts
      - uses: actions/checkout@v4
        with:
          ref: main-deploy

      - name: Build release message
        id: release_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Push tag
        run: |
          git config user.name "Release Bot"
          git config user.email "not.real@example.com"
          git push origin "HEAD:refs/tags/$TAG"
        env:
          TAG: ${{ needs.compute_tags.outputs.release_tag }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.compute_tags.outputs.release_tag }}
          release_name: ${{ needs.compute_tags.outputs.release_tag }}
          body: |
            This release includes generated configuration artifacts that are dependent on a successful version bump.
            ### Links
            * [Pull Request diff](https://github.com/${{ github.repository }}/compare/${{ github.sha }}..${{ needs.compute_tags.outputs.release_tag }})
            * [Changes since last release](https://github.com/${{ github.repository }}/compare/${{ needs.compute_tags.outputs.last_release_tag }}..${{ needs.compute_tags.outputs.release_tag }})
        env:
          GITHUB_TOKEN: ${{ github.token }}