name: Continuous Integration

on: push

env:
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  ENV: production
  ROLLBAR_CLIENT_TOKEN: ${{ secrets.ROLLBAR_CLIENT_TOKEN }}
  VERSION: test

jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: Unit tests
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: rdc_website_test
          POSTGRES_PASSWORD: junkdata
          POSTGRES_DB: rdc_website_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: red-door-collective 
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop --impure -c ./test-setup.sh /tmp
      - run: nix develop --impure -c pytest
      - run: nix-shell --run "pytest"

  integration_tests:
    runs-on: ubuntu-latest
    name: Integration tests
    defaults:
      run:
        shell: bash
        working-directory: pages 
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # Re-use node_modules between runs until package-lock.json changes.
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: node_modules-node-v${{ matrix.node }}-${{ hashFiles('package-lock.json') }}

      # Re-use ~/.elm between runs until elm.json, elm-tooling.json or
      # review/elm.json changes. The Elm compiler saves downloaded Elm packages
      # to ~/.elm, and elm-tooling saves downloaded tool executables there.
      - name: Cache ~/.elm
        uses: actions/cache@v4
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}

      # Install npm packages, unless we restored them from cache.
      # Since `npm ci` removes the node_modules folder before running it’s
      # important to skip this step if cache was restored.
      - name: npm ci
        # if: steps.cache-node_modules.outputs.cache-hit != 'true'
        env:
          # If you have a `"postinstall": "elm-tooling install"` script in your
          # package.json, this turns it into a no-op. We’ll run it in the next
          # step because of the caching. If elm-tooling.json changes but
          # package-lock.json does not, the postinstall script needs running
          # but this step won’t.
          NO_ELM_TOOLING_INSTALL: 1
        run: npm ci
      - name: elm-tooling install
        run: npx --no-install elm-tooling install
      - uses: nick-invision/retry@v2
        name: Build
        with:
          max_attempts: 3
          timeout_minutes: 3
          retry_on: error
          command: cd pages && npm install && npm run build
      - name: Tests
        run: npm test
        env:
          GITHUB_TOKEN: secrets.GITHUB_TOKEN
      - name: Add elm-review, elm and elm-format to path
        run: npm bin >> $GITHUB_PATH
      # - uses: sparksp/elm-review-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: elm-format
        # run: npx --no-install elm-format --validate src/
      - name: Setup for cypress
        run: (npm install && npx elm-tooling install)
      - name: Install Cypress
        run: npm i cypress
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:1234"
          wait-on-timeout: 60
          working-directory: pages
          install: false
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: pages/cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: pages/cypress/videos

  compute_tags:
    name: Compute Tags
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.compute_tag.outputs.next_tag }}
      last_release_tag: ${{ steps.compute_tag.outputs.previous_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute release tag
        id: compute_tag
        uses: craig-day/compute-tag@v13
        with:
          github_token: ${{ github.token }}
          version_scheme: continuous
          version_type: major
          
  commit_assets:
    runs-on: ubuntu-latest
    name: Commit Assets
    needs:
      - compute_tags
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: cachix/install-nix-action@v20
      - uses: nick-invision/retry@v2
        name: Build application
        with:
          max_attempts: 3
          timeout_minutes: 3
          retry_on: error
          command: ./scripts/build-ui
        env:
          VERSION: ${{ needs.compute_tags.outputs.release_tag }}
      - id: commit_assets
        run: |
          set -ex -o pipefail
          git config user.name "Release Bot"
          git config user.email "not.real@example.com"
          git add -f rdc_website/static_pages
          git commit -m "Build application for $GITHUB_SHA"
          
          BRANCH_NAME="$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///')-deploy"

          git push --force origin "HEAD:refs/heads/$BRANCH_NAME"
          echo "::set-output name=git_branch::$BRANCH_NAME"
  
  release:
    name: Create Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: 
      - commit_assets
      - compute_tags
    steps:
      # Checkout the ref that contains artifacts
      - uses: actions/checkout@v4
        with:
          ref: main-deploy

      - name: Build release message
        id: release_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Push tag
        run: |
          git config user.name "Release Bot"
          git config user.email "not.real@example.com"
          git push origin "HEAD:refs/tags/$TAG"
        env:
          TAG: ${{ needs.compute_tags.outputs.release_tag }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.compute_tags.outputs.release_tag }}
          release_name: ${{ needs.compute_tags.outputs.release_tag }}
          body: |
            This release includes generated configuration artifacts that are dependent on a successful version bump.
            ### Links
            * [Pull Request diff](https://github.com/${{ github.repository }}/compare/${{ github.sha }}..${{ needs.compute_tags.outputs.release_tag }})
            * [Changes since last release](https://github.com/${{ github.repository }}/compare/${{ needs.compute_tags.outputs.last_release_tag }}..${{ needs.compute_tags.outputs.release_tag }})
        env:
          GITHUB_TOKEN: ${{ github.token }}